version: 2

models:
  - name: stg_reg_cards
    description: registration cards from a veterinary clinic about pets and their owners
    columns:
      - name: patient_id
        description: Primary key 
        data_tests:
          - unique
          - not_null
      - name: owner_id
        description: Unique identifier for the pet's owner
        data_tests:
          - unique
          - not_null
      - name: gender 
        description: Gender of pets 
        data_tests:
          - accepted_values:
              values: ['Male', 'Female']
  - name: stg_visits
    description: 
    columns:
      - name: patient_id
        description: Unique identifier for the pet
        data_tests:
          - not_null
          - relationships:
            to: ref('stg_reg_cards')
            field: patient_id
